name: Smart Greenhouse Production

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      # - name: Pull Docker images for cache
      #   run: |
      #     docker pull ${{ secrets.DOCKER_USERNAME }}/smart-greenhouse-backend:latest || true

      - name: Build Docker images
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/smart-greenhouse-backend:latest .

      - name: Push to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/smart-greenhouse-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE_CONTENT }}" > .env

      - name: Copy docker-compose.yml and .env to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose.yml,.env"
          target: "~/smart-greenhouse/"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/smart-greenhouse
            echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker pull ${{ secrets.DOCKER_USERNAME }}/smart-greenhouse-backend:latest
            docker rm -f smart-greenhouse-backend || true
            docker compose up -d
